<a href="https://colab.research.google.com/github/AFauzulh/MK-Sistem-Cerdas/blob/main/Hebb_Net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Tugas Sistem Cerdas Hebb Net</h1>

Nama  : Alfirsa Damasyifa Fauzulhaq

NIM   : 226150100111019

Kelas : Sistem Cerdas - B

# Versi PPT (Biner Tanpa Bias)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def activation_function(y_in):
  return 1 if y_in > 0 else 0

def accuracy_score(preds, real):
  correct = 0
  for i, _ in enumerate(real):
    if preds[i] == real[i]:
      correct+=1
  
  return correct/len(real)

In [3]:
class Hebb_Net():
  def __init__(self, n_features=4, n_class=2):
    # inisialisasi bobot awal
    self.n_features = n_features
    self.n_class = n_class
    self.weight = np.zeros((n_features, n_class))

  def train(self, X, Y, verbose=False):
    for x, y in zip(X, Y):
      for i, _ in enumerate(self.weight):
        for j, _ in enumerate(self.weight[i]):
          # urutan update bobot (w) => [11, 21], [12, 22], [13, 23], [14, 24]
          self.weight[i][j] = self.weight[i][j] + (x[i]*y[j])

      if verbose:
        print(f"Bobot-bobot jaringan:\n{self.weight}")

  def predict(self, x):
    pred = []

    for i in range(self.n_class):
      y_pred = np.dot(x, self.weight[:, i])
      y_pred = activation_function(y_pred)
      pred.append(y_pred)

    return pred

In [4]:
X = [[1,0,0,0], [1,1,0,0], [0,0,0,1], [0,0,1,1]]
Y = [[1,0],[1,0],[0,1],[0,1]]

hebb = Hebb_Net()
hebb.train(X, Y, verbose=True)

Bobot-bobot jaringan:
[[1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Bobot-bobot jaringan:
[[2. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]]
Bobot-bobot jaringan:
[[2. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]]
Bobot-bobot jaringan:
[[2. 0.]
 [1. 0.]
 [0. 1.]
 [0. 2.]]


In [5]:
preds = []
for x in X:
  preds.append(hebb.predict(x))

print(preds)

[[1, 0], [1, 0], [0, 1], [0, 1]]


In [6]:
# testing
x = [0,0,1,1]
print(hebb.predict(x))

[0, 1]


In [7]:
x = [0,1,0,0]
print(hebb.predict(x))

[1, 0]


In [8]:
x = [0,1,1,0]
print(hebb.predict(x))

[1, 1]


# Studi Kasus Gerbang Logika (Bipolar Dengan Bias)

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [10]:
def accuracy_score(preds, real):
  correct = 0
  for i, _ in enumerate(real):
    if preds[i] == real[i]:
      correct+=1
  
  return correct/len(real)

def bipolar_activation_function(y_in):
  return 1 if y_in >= 0 else -1 

In [11]:
class Hebb_Net():
  def __init__(self, n_features=4, n_class=2):
    # inisialisasi bobot awal
    self.n_features = n_features
    self.n_class = n_class
    self.weight = np.zeros((n_features, n_class))
    self.bias = 1
    self.wb = 0

  def train(self, X, Y, verbose=False):
    for x, y in zip(X, Y):
      for i, _ in enumerate(self.weight):
        for j, _ in enumerate(self.weight[i]):
          # urutan update bobot (w) => [11, 21], [12, 22], [13, 23], [14, 24]
          self.weight[i][j] = self.weight[i][j] + (x[i]*y[j])

      # update bobot bias
      for target in y:
        self.wb = self.wb + (self.bias*target)

      if verbose:
        print(f"Bobot-bobot jaringan:\n{self.weight}")
        print(f"Bobot Bias:{self.wb}")

  def predict(self, x):
    pred = []

    for i in range(self.n_class):
      y_pred = np.dot(x, self.weight[:, i]) + (self.bias*self.wb)
      y_pred = bipolar_activation_function(y_pred)
      pred.append(y_pred)

    return pred

## AND

In [12]:
X = [(1, 1), (1, -1), (-1, 1), (-1, -1)]
Y = [[1], [-1], [-1], [-1]]
hebb = Hebb_Net(n_features=2, n_class=1)
hebb.train(X, Y, verbose=False)

preds = []
for x in X:
  preds.append(hebb.predict(x))

accuracy = accuracy_score(preds, Y)
print(accuracy)

1.0


## OR

In [13]:
X = [(1, 1), (1, -1), (-1, 1), (-1, -1)]
Y = [[1], [1], [1], [-1]]
hebb = Hebb_Net(n_features=2, n_class=1)
hebb.train(X, Y, verbose=False)

preds = []
for x in X:
  preds.append(hebb.predict(x))

accuracy = accuracy_score(preds, Y)
print(accuracy)

1.0


## AND NOT

In [14]:
X = [(1, 1), (1, -1), (-1, 1), (-1, -1)]
Y = [[-1], [1], [-1], [-1]]
hebb = Hebb_Net(n_features=2, n_class=1)
hebb.train(X, Y, verbose=False)

preds = []
for x in X:
  preds.append(hebb.predict(x))

accuracy = accuracy_score(preds, Y)
print(accuracy)

1.0
